git clone --recurse https://github.com/21kHz/21kHz-rack-plugins
git clone --recurse https://github.com/alikins/Alikins-rack-plugins
git clone --recurse https://github.com/alto777/LFSR
git clone --recurse https://github.com/jhoar/AmalgamatedHarmonics
git clone --recurse https://github.com/aptrn/aP-Modules.git
git clone --recurse https://github.com/adbrant/ArableInstruments
git clone --recurse https://github.com/ArjoNagelhout/arjo_modules
git clone --recurse https://github.com/AScustomWorks/AS
git clone --recurse https://github.com/VCVRack/AudibleInstruments
git clone --recurse https://github.com/antoniograzioli/Autodafe-Drums
git clone --recurse https://github.com/antoniograzioli/Autodafe
git clone --recurse https://github.com/av500/vcvrackplugins_av500
git clone --recurse https://github.com/baconpaul/BaconPlugs
git clone --recurse https://github.com/tnorris/BBI.git
git clone --recurse https://github.com/chrisbeckstrom/Beckstrom_Research_Rack
git clone --recurse https://github.com/VCVRack/Befaco
git clone --recurse https://github.com/sebastien-bouffier/Bidoo
git clone --recurse https://github.com/bogaudio/BogaudioModules
git clone --recurse https://github.com/bokontep/BokontepByteBeatMachine
git clone --recurse https://github.com/KieranPringle/CastleRocktronics
git clone --recurse https://github.com/cfoulc/cf
git clone --recurse https://github.com/JerrySievert/CharredDesert
git clone --recurse https://github.com/freddyz/computerscare-vcv-modules
git clone --recurse https://github.com/dBiz/dBiz
git clone --recurse https://github.com/dekstop/vcvrackplugins_dekstop
git clone --recurse https://github.com/dhemery/DHE-Modules/
git clone --recurse https://github.com/JerrySievert/DrumKit
git clone --recurse https://github.com/VCVRack/ESeries
git clone --recurse https://github.com/bafonso/Erratic
git clone --recurse https://github.com/FrankBuss/Formula
git clone --recurse https://github.com/almostEric/FrozenWasteland
git clone --recurse https://github.com/VCVRack/Fundamental
git clone --recurse https://github.com/MarcBoule/Geodesics
git clone --recurse https://github.com/gratrix/vcv-gratrix
git clone --recurse https://github.com/mhetrick/hetrickcv
git clone --recurse https://github.com/dhuber81/huaba
git clone --recurse https://github.com/MarcBoule/ImpromptuModular
git clone --recurse https://github.com/eres-j/VCVRack-plugin-JE
git clone --recurse https://github.com/jeremywen/JW-Modules
git clone --recurse https://github.com/KarateSnoopy/vcv-karatesnoopy
git clone --recurse https://github.com/koralfx/Koralfx-Modules/
git clone --recurse https://github.com/lindenbergresearch/LRTRack
git clone --recurse https://github.com/leopard86/LOGinstruments
git clone --recurse https://github.com/luckyxxl/vcv_luckyxxl
git clone --recurse https://github.com/a2aaron/VCVMicroTools.git
git clone --recurse https://github.com/martin-lueders/ML_modules
git clone --recurse https://github.com/dllmusic/VCV_moDllz
git clone --recurse https://github.com/cschol/modular80
git clone --recurse https://github.com/djpeterso23662/MrLumps
git clone --recurse https://github.com/mschack/VCV-Rack-Plugins
git clone --recurse https://github.com/naus3a/NauModular
git clone --recurse https://github.com/joelrobichaud/Nohmad
git clone --recurse https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins
git clone --recurse https://github.com/DomiKamu/Ohmer-Modules
git clone --recurse https://github.com/adbrant/ArableInstruments
git clone --recurse https://github.com/imekon/PG-Instruments
git clone --recurse https://github.com/bongozone/vcvrack-rtlsdr
git clone --recurse https://github.com/phdsg/PvC
git clone --recurse https://github.com/raincheque/qwelk
git clone --recurse https://github.com/Miserlou/RJModules
git clone --recurse https://github.com/RODENTCAT/RODENTMODULES
git clone --recurse https://github.com/s-ol/vcvmods
git clone --recurse https://github.com/josbouten/Sculpt-O-Sound
git clone --recurse https://github.com/apbianco/SerialRacker
git clone --recurse https://github.com/IohannRabeson/VCVRack-Simple
git clone --recurse https://gitlab.com/sonusdept/sonusmodular
git clone --recurse https://github.com/gbrandt1/southpole-vcvrack
git clone --recurse https://github.com/squinkylabs/SquinkyVCV
git clone --recurse https://github.com/stellare-modular/vcv-link
git clone --recurse https://github.com/teletypist/stochasm
git clone --recurse https://github.com/Strum/Strums_Mental_VCV_Modules
git clone --recurse https://github.com/david-c14/submarine-prototype-vcv/
git clone --recurse https://github.com/david-c14/SubmarineFree/
git clone --recurse https://github.com/david-c14/SubmarineUtility/
git clone --recurse https://github.com/JerrySievert/SynthKit
git clone --recurse https://github.com/david-c14/Torpedo
git clone --recurse https://github.com/JTriggerFish/TriggerFish-VCV.git
git clone --recurse https://github.com/j4s0n-c/trowaSoft-VCV
git clone --recurse https://gitlab.com/unlessgames/unless_modules
git clone --recurse https://github.com/The-XOR/RackPlugins
git clone --recurse https://github.com/ValleyAudio/ValleyRackFree/

